# Generated by 'click-buildtool elem2make' on Sex Jun 23 14:55:26 -03 2017
ELEMENT_OBJS__0 = \
checkdhcpmsg.u.o \
dhcpclassifier.u.o \
dhcpclient.u.o \
dhcpicmpencap.u.o \
dhcpoptionutil.u.o \
dhcpserverack.u.o \
dhcpserveroffer.u.o \
dhcpserverrelease.u.o \
leasehash.u.o \
leasepool.u.o \
leasetable.u.o \

ELEMENT_OBJS = \
$(ELEMENT_OBJS__0) \

$(ELEMENT_OBJS__0): %.u.o: ./%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
	$(FIXDEP)
$(patsubst %.u.o,%.s,$(ELEMENT_OBJS__0)): %.s: ./%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.u.o,%.ii,$(ELEMENT_OBJS__0)): %.ii: ./%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

